openedx/blockstore

Makefile, blockstore/settings/base.py, blockstore/settings/production.py, requirements/base.txt, requirements/production.txt
This PR fixes some of the errors seen during automated deployment. The errors were related to missing keys in logging object, changes in syntax from python2 to python3 and additional packages required to apply django migrations.
of the changes.
- TODO: Squash commits into discrete sets of changes (see the note about release notes above)
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
=> Changes to settings and requirements file required for deployment

decisions/0001-bundle-granularity.rst
@symbolist, @bradenmacdonald: A hopefully more fleshed out overview of what I was proposing. I'm channeling the Nimisha-angel on my shoulder and writing it up as an arch decision record, though I realize that we're just as likely to go with one of the other proposals. (I think once we do figure this out, it needs to be arch decision record number 1 for this repo.)
=> Bundle Granularity writeup for Flat, One-Bundle Course proposal

requirements/base.txt
=> Add edx-django-release-util dependency

requirements/production.txt
=> Add Boto3 lib dependency.

.circleci/config.yml
Add python 3.8 to the matrix of tests.
=> [BD-6] Add tests with python 3.8

.github/workflows/docker-publish.yml, Dockerfile, Makefile
This will allow us to publish Docker images to Dockerhub.
=> WIP: Add new dockerfile and github action to publish it

README.rst
The README is missing a lot of useful information about how to use Blockstore today. This PR brings it up to date.
=> Update README to be more helpful

blockstore/apps/api/v1/tests/test_contract.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2040
=> BOM-2040 : Post Python 3.8 changes

requirements/base.txt, requirements/local.txt, requirements/production.txt, requirements/test.txt
This is to make sure that we use the same Django version for all applications.
See: https://openedx.atlassian.net/jira/software/projects/BTR/boards/641?selectedIssue=BTR-30
This is ready for review -- cc @nedbat
=> Upgrade Django to 2.2.17

README.rst
In working on this ticket: https://openedx.atlassian.net/browse/TNL-8485 , I discovered a few places where the documentation needed an update. The needed updates are in this PR, including more details on how to run integration tests against an specific Elasticsearch instance in a Docker container.
=> docs: Fix test typo and update/correct devstack commands.

blockstore/apps/bundles/store.py, blockstore/apps/bundles/tests/test_store.py
Change Draft and Version store metadata to track static file's MIME type based on its "file extension" as defined by [`mimetypes.guess_type()`](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type). Additionally, sets the extension based on the guessed mime type when saving files in the Version Store, in an attempt to allow correct MIME type headers when serving the files.
Finally, the change is backward compatible. If a file's MIME type cannot be guessed from its extension or the file doesn't have an extension at all, it is stored using the old naming schema (that is, only the file's hash). This also allows files stored with the old metadata that doesn't carry the `mime_type` field to be handled correctly.
See additional discussion in the related issue #63.
The PR …
=> Add MIME type based file extensions to snapshot data files [SE-4663] 

.github/workflows/migrations-check-mysql8.yml
=> build: add check for running migraitons on mysql 8.0

.github/workflows/upgrade-python-requirements.yml
=> chore: update tnl alert endpoint

blockstore/apps/rest_api/v1/views/bundles.py, blockstore/apps/rest_api/v1/views/collections.py, blockstore/apps/rest_api/v1/views/drafts.py, blockstore/settings/production.py
=> fix: permission classes and remove default

requirements/pip-tools.txt
=> chore: pip tools v6.6.1

blockstore/settings/base.py
**Issue:** [BOM-3449](https://2u-internal.atlassian.net/browse/BOM-3449)
- Added `CookieMonitoringMiddleware` in settings.
=> build: add cookie monitoring middleware

README.rst, tagstore/README.rst
This repository's README was a bit out of date. This PR makes some changes to bring it up to date. More work will be needed in future PRs.
I also reinstated the Tagstore README, [per the recent discussion about it on the forum](https://discuss.openedx.org/t/guidance-needed-on-processing-course-content-text-in-course-discovery/8160).
Not sure if any testing is needed. Just look for typos and make sure the links work and the information is accurate.
=> docs: Update READMEs for Blockstore and Tagstore

.github/workflows/pypi-publish.yml
This PR adds the publish workflow to start publishing the package to PyPI
=> Add publish to pypi workflow

setup.py
Reverts openedx/blockstore#214
=> Revert "Fix package name"

blockstore/__init__.py
=> Bump version for next release

requirements/base.txt, requirements/local.txt, requirements/production.txt, requirements/test.txt
See: https://github.com/openedx/wg-build-test-release/issues/282
=> chore: upgrade Django to 3.2.19

README.rst
=> docs: update devstack docs nit

requirements/base.txt, requirements/local.txt, requirements/production.txt, requirements/test.txt
See: https://github.com/openedx/wg-build-test-release/issues/297
=> chore: upgrade Django to 3.2.20

README.rst
=> docs: differ between usage and development setup instructions.

requirements/base.txt, requirements/local.txt, requirements/production.txt, requirements/test.txt
See: https://github.com/openedx/wg-build-test-release/issues/303
=> chore: upgrade Django to 3.2.21

requirements/base.txt, requirements/local.txt, requirements/production.txt, requirements/test.txt
See: https://github.com/openedx/wg-build-test-release/issues/338
=> chore: update Django to 3.2.24 for Quince - Security Patch

CHANGELOG.rst, README.rst, blockstore/__init__.py, setup.py
Ref: https://github.com/openedx/blockstore/issues/314
=> feat!: mark the repository as deprecated (v1.4.1)
