openedx/blockstore

Dockerfile-dev
Makefile
blockstore/apps/api/tests/test_utils.py
blockstore/apps/api/utils.py
blockstore/apps/api/v1/serializers/bundles.py
blockstore/apps/api/v1/serializers/snapshots.py
blockstore/apps/api/v1/tests/test_serializers.py
blockstore/apps/api/v1/tests/test_views.py
blockstore/apps/api/v1/views/bundles.py
blockstore/apps/api/v1/views/snapshots.py
blockstore/apps/bundles/models.py
blockstore/apps/bundles/store.py
blockstore/apps/bundles/tests/test_models.py
blockstore/settings/base.py
requirements/base.txt
requirements/test.txt

Provides several improvements to the REST API, detailed below.
**JIRA tickets**:  LX-53, SE-281
**Testing instructions**:
* Visit http://localhost:8888/api/v1/bundle/ and view a bundle version.
* Visit http://localhost:8888/api/v1/bundle_versions/ and view a bundle version.
* Append `?expand=files` to the urls above, and note that the `files` hyperlink is converted to an array of files data, which matches what was shown by following the `files` hyperlink.
* Appending `?expand=files&format=json` also works.
* Appending `?expand=files` to the `/api/v1/bundle/` and `/api/v1/bundle_versions/` list views has no effect (previous to f47b553, it threw an error).
* list Bundles associated with a Collection, e.g. 
http://localhost:8888/api/v1/bundles/?collection__uuid=4ffa83df9b93499e91c29f5a7ad9
* …

LX-53 REST API improvements

---

blockstore/apps/mysql_unicode/__init__.py
blockstore/apps/mysql_unicode/migrations/0001_initial.py
blockstore/settings/base.py
blockstore/settings/local.py
blockstore/settings/production.py
blockstore/settings/test.py
tagstore/backends/django.py
tagstore/backends/tagstore_django/migrations/0001_initial.py
tagstore/backends/tagstore_django/models.py
tagstore/backends/tests.py
tagstore/models/tag.py
tagstore/tagstore.py

When I rebased https://github.com/open-craft/blockstore/pull/7 in preparation for merge, a couple tests broke (specifically, emoji tags weren't working and case-sensitive tags + case-insensitive search was not working). Here's what eventually I arrived at to fix them.
This PR:
* Uses a migration to force Blockstore's MySQL database to use the `utf8mb4` encoding and `utf8mb4_unicode_ci` collation. These are generally recommended by everyone for new projects, and we already had some design decisions in place to be compatible with those. (However, without the fixes in this PR, it wasn't actually possible to use blockstore with `utf8mb4`)
* Changes tagstore from being case-sensitive for tags to "preserve case but tags must be case-insensitively unique". I think that's better anyways, and it …

Update Tagstore to work with MySQL, Blockstore to work with utf8mb4

---

tagstore/README.rst
tagstore/backends/django.py
tagstore/backends/tagstore_django/migrations/0001_initial.py
tagstore/backends/tagstore_django/models.py
tagstore/backends/tests.py
tagstore/models/__init__.py
tagstore/models/tag.py
tagstore/models/taxonomy.py
tagstore/tagstore.py

A few last API improvements to make this tagstore API a bit nicer, before we get too locked in.
* Per @symbolist's suggestion, `Tag.tag` is now `Tag.name` which I think is much nicer
* The API was missing a way to get an existing `Tag` without constructing it yourself, so I added a `get_tag()` method
* Made the `Taxonomy` class a bit more pythonic by giving it some methods, so now you can do `taxonomy.add_tag('foo')` instead of `tagstore.add_tag_to_taxonomy('foo', taxonomy)`
Testing instructions:
* The unit tests should cover everything quite well, so mostly review the code. You can also run the updated example code from `README.rst`.

Tagstore API improvements

---

blockstore/templates/admin/tagstore_django/tag_hierarchy.html
tagstore/backends/django.py
tagstore/backends/tagstore_django/models.py
tagstore/backends/tagstore_django/templatetags/tagstore_admin.py

@bradenmacdonald I am sorry for opening another PR on this branch, but I discovered a bug. The Django admin uses the same template for both change and add. There's no `taxonomy_uid` on the add page because it hasn't been created yet, so the call to `get_tags_in_taxonomy_hierarchically_as_dict` raises an exception when it tries to cast `taxonomy_uid` to an int.
ETA: Also fixed an issue with KeyErrors caused by uppercase letters in parent tags.
1. Go to http://0.0.0.0:18250/admin/tagstore_django/taxonomy/add/ , with and without this commit

Fix missing taxonomy_uid in templatetag

---

blockstore/settings/local.py
blockstore/settings/test.py

This PR fixes the logging issue seen in devstack after #18 was merged, during web-requests and running tests.
To test it:
1. Start the server inside the shell, and make any request. There should not be any logging errors seen on the console.
2. From inside the shell, run the test scripts with `make validate`. There should not be any logging errors seen.

Fix the logging error in devstack

---

.circleci/config.yml
blockstore/apps/api/v1/urls.py
blockstore/apps/search/apps.py
blockstore/apps/search/core/README.md
blockstore/apps/search/core/documents.py
blockstore/apps/search/core/fieldsets.py
blockstore/apps/search/core/serializers.py
blockstore/apps/search/core/tests/test_base.py
blockstore/apps/search/core/tests/test_documents.py
blockstore/apps/search/core/viewsets.py
blockstore/apps/search/documents.py
blockstore/apps/search/fieldsets.py
blockstore/apps/search/tests/test_documents.py
blockstore/apps/search/tests/test_views.py
blockstore/apps/search/views.py
blockstore/settings/base.py
docker-compose.yml
requirements/base.txt

This is the first iteration of search capabilities in Blockstore. It adds the following:
- An index and document mapping which can store the data needed for first version of LX search.
- A REST API which can be used to create, edit and delete ES documents in the default index and to query them.
- This has the minimum amount of functionality needed for the first prototype of the LX search interface. A lot more will be added once we are clear what the data sources are going to be, what the shape of the ownership, authorship, and permissions data is going to be and what query patterns will need to be supported.
- ES queries are described in JSON and ES [expects](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html) queries to use a GET request with a body …

Init search engine.

---

Makefile
blockstore/settings/production.py
docker-compose.yml
requirements/production.txt

- Adds a Make command to collect static assets.
- Fixes an import bug in `settings/production.py`.
- Adds 'rest_framework.authentication.BasicAuthentication' to production. We will later need to change this to OAuth.
- Adds missing newrelic dependency.
- Adds a docker volume for the venv so that provisioning is not needed on every up.
These changes are being used to provision servers for LX stage and preview. Check that provisioning of Blockstore service completes successfully.

Elastic Stack configuration

---

requirements/production.txt

This fix removes the duplicate mysql requirements in the production.txt file. The requirement for mysql is already part of base.txt and the duplication in production.txt results in the failure of `make production-requirements` command.

Remove duplicate mysql requirement

---

README.rst
blockstore/settings/base.py

This is a quick follow-up to #38, to remove a workaround now that I know what settings on the LMS must be changed for the SSO flow to work as intended.
Check out this branch and restart Blockstore. Configure your devstack per the updated README instructions in this PR, then login to Blockstore by going to http://localhost:18250/login in an incognito window.
Then go to http://localhost:18250/admin/social_django/usersocialauth/ and click on the user you used (e.g. "staff") and confirm that the user_id is present in the "Extra Data" JSON field.

Properly fetch user_id during LMS SSO flow

---

blockstore/apps/api/permissions.py
blockstore/apps/api/tests/__init__.py
blockstore/apps/api/v1/tests/test_authorization.py
blockstore/apps/api/v1/tests/test_contract.py
blockstore/settings/base.py
tagstore/tagstore_rest/v1/tests/test_views.py

We want to ensure that even if the Blockstore REST API is accidentally exposed to the public internet, it will not accept any requests from unauthorized users/applications.
This PR restricts API access to:
* Users with superuser permission (so LMS admins can login via SSO and then use both the API and the django admin)
* Application service users that [authenticate with a valid token header](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) - this is how the LMS will authenticate itself.
Most Open edX IDAs use OAuth2 authentication; I tried using that initially but it turns out that django-oauth-toolkit is incompatible with the `utf8mb4` database encoding that Blockstore uses. Using a token header is simpler, faster, and perfectly secure, provided that …

Add authorization to Blockstore API [SE-1255]

---

blockstore/apps/core/models.py

Feanil asked me to take a look at this repo to see if the most recent DOT/JWT-based authentication was being used. Naturally, everything was fine! But there were a couple of incorrect comments lingering about OIDC. This PR simply changes those comments.
Nothing to test.

Fix comments referring to OpenID Connect.

---

blockstore/settings/base.py

We added it as a requirement but forgot to add it to the list of installed apps.

Add release_util to the list of installed apps.

---

blockstore/apps/api/v1/tests/test_contract.py
blockstore/apps/bundles/migrations/0001_initial.py
blockstore/apps/bundles/models.py

Allow description to be blank when creating a bundle
I assume we don't care if bundles have blank descriptions? I left slug as required.
If we want to insist on requiring descriptions, it's fine to close this PR.

Allow description to be blank when creating a bundle

---

blockstore/apps/api/v1/tests/test_contract.py
blockstore/apps/api/v1/views/drafts.py

Due to a minor oversight, it wasn't possible to delete a draft using the REST API.
Go to http://localhost:18250/api/v1/drafts and click on any draft. Notice the "Delete" button is missing (and if it was there it would raise an error). Check out this branch. Refresh. Now it's present and will work.

Allow deleting draft via REST API

---

blockstore/apps/api/v1/serializers/bundles.py
blockstore/apps/api/v1/serializers/drafts.py
blockstore/apps/api/v1/tests/test_contract.py

APIs returned by Blockstore [should](https://www.django-rest-framework.org/api-guide/reverse/) always be absolute, but currently the BundleVersion serializer sometimes returns relative URLs (if using local file media storage). This requires the client to be able to convert those to absolute URLs which is a pain.

Fix: the API should only return absolute URLs

---

Makefile
README.rst

This PR reduces the `make dev.up`, [`make provision`,] `make blockstore-shell`, `make runserver`, and `make stop` steps into a single `make easyserver` command.

Add an even easier way to run the service

---

blockstore/apps/api/v1/serializers/bundles.py
blockstore/apps/api/v1/tests/test_contract.py

The `slug` field has `allow_unicode=True`, but the DRF serializer was rejecting unicode characters if you tried to use the REST API to create a bundle with a unicode slug.
I know we may just remove the slug field altogether but this is an easy fix for now.

Fix: could not set unicode slugs via the REST API

---

blockstore/apps/bundles/store.py

Boto3 doesn't convert from Unicode values in a graceful way.

Force ContentFile to hold binary values.

---

blockstore/apps/bundles/store.py

The default for this was different between Django's built-in file
storage and boto3's S3 storage, causing decoding issues in Python
3.5 (Python 3.6 changes json.load() to work with files that are
opened in either str or binary mode).

Force consistent binary reads of JSON data.

---

Dockerfile-dev
Makefile

This fixes installing the cffi python library (a dependency of a dependency). Building cffi requires libffi-dev installed. 
This also adds a `pull` make target as a convenience to update the underlying docker image, and removes the quiet flag from some pip install commands to help debugging.
Because docker aggresively caches things, others could run into this problem even with this patch included. Perhaps we need a note in the readme and/or a make target to point towards running `docker-compose build --no-cache` to force rebuild the blockstore image?
1. `make destroy` to begin with a clean slate
1. `make pull` to update the docker base image
1. `docker-compose build --no-cache` to rebuild the docker image
1. `make easyserver` to provision and build the blockstore instance
1. verify that …

Add missing dependency

---

.circleci/config.yml
blockstore/apps/api/routers.py
blockstore/apps/api/v1/tests/test_contract.py
blockstore/apps/api/v1/views/drafts.py
blockstore/apps/bundles/links.py
blockstore/apps/bundles/models.py
blockstore/apps/bundles/store.py
blockstore/apps/bundles/tests/test_models.py
blockstore/apps/bundles/tests/test_store.py
blockstore/apps/core/constants.py
blockstore/apps/core/models.py
blockstore/apps/core/tests/test_models.py
blockstore/settings/base.py
requirements/test.txt
tagstore/backends/tagstore_django/templatetags/tagstore_admin.py
tagstore/backends/tests/test_backends.py
tagstore/tagstore_rest/v1/tests/test_views.py
tagstore/tagstore_rest/v1/views/entities.py

This is a fix for #54.
It also:
* Includes a ton of minor pylint fixes to get the build passing again with the current version of `edx-lint`
* Fixes the logging configuration to stop every request from being logged twice.

Fix #54: PATCHing a draft resets its links

---

openedx.yaml

This adds an `openedx.yaml` file now that Blockstore is part of the `edx` org, and so that it can be tagged for Open edX named releases in the future.
FYI @nedbat

Add openedx.yaml (OEP-2 & OEP-10)

---

decisions/0002-app-not-service.rst

Blockstore will remain a separate application and repo, but be added as an installed app to Studio and will run in-process.

ADR for Blockstore as App

---

blockstore/apps/api/v1/tests/test_contract.py
blockstore/apps/api/v1/views/bundles.py
requirements/base.txt

This PR introduces filters used by edx/edx-platform#24530 and edx/edx-platform#24510. This adds support for:
- filtering bundles by UUIDs, so that we can get data about multiple bundles in a single API call.
- searching the Title, Description and Slug of the bundles
**Testing instructions:**
- Run `make test` in `make blockstore-shell`
- Create a couple of bundles using the existing API
- Verify that `uuid` query param works in the `GET /api/v1/bundles?uuid={uuid1},{uuid2}` request
Reviewers:
[ ] @arbrandes
[ ] edX reviewer[s] TBD

[BD-14] Add support for filtering bundles

---

.circleci/config.yml
Dockerfile-3.8
Makefile
blockstore/settings/base.py
blockstore/settings/local.py
blockstore/settings/test.py
docker-compose-3.8.yml
docker-compose-testserver-3.8.yml

This upgrades the blockstore to use the MySQL 5.7 container as its backend, and also updates CircleCI to use it in testing. It also changes the Dockerfile to use Ubuntu 20.04 instead of Alpine to better match other devstack images and prove compatibility.
https://openedx.atlassian.net/browse/TNL-7642
The directions in https://openedx.atlassian.net/wiki/spaces/AC/pages/1135181906/Upgrade+base+OS+from+Ubuntu+16.04+to+20.04 involve access to a lot of sandbox tools that I do not have access to. It would be best if the requirements not covered by this PR were handled by an edX team member.
Stop any running copies of blockstore. Remove all blockstore cache volumes:
```
docker volume rm blockstore38_blockstore_venv_3_8_5
docker volume rm blockstore-testserver38_blockstore_venv_3_8_5
```
**Note** …

[TNL-7642] [SE-3536] Switch MySQL backends to 5.7.

---

blockstore/settings/base.py
blockstore/urls.py
requirements/base.in
requirements/base.txt
requirements/docs.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

This PR adds the changes to use edx-api-doc-tools instead of django-swagger
As I mentioned in another PR, this [will only display](https://github.com/edx/api-doc-tools/issues/27) in  /api-docs/ the APIs that are in the /api/ path (it will not display the tagstore APIs),
Run the server and go to the /api-docs/, that should look like this:

Use edx-api-doc-tools instead of deprecated django-swagger

---

Makefile
README.rst
docker-compose-3.8.yml
docker-compose-testserver-3.8.yml

This allows for multiple edX devstacks (introduced via https://github.com/edx/devstack/pull/532) by letting the user specify which compose project to target.
It also adds a couple of convenience Makefile targets.
For the simplest test, pulling in this PR should not affect the maintenance of an existing devstack, or creating a new one as usual.
To actually test the feature introduced here, one must first create a new Open edX devstack using a separate compose project.  See [the instructions in the README](https://github.com/edx/devstack/blob/master/README.rst#how-do-i-run-multiple-named-open-edx-releases-on-same-machine).  Then, export OPENEDX_PROJECT_NAME accordingly and check if blockstore provisions and runs correctly.

Support multiple Open edX devstacks

---

Makefile

ubuntu:20.04 is now used in the Dockerfile
**JIRA tickets**: [OSPR-5283](https://openedx.atlassian.net/browse/OSPR-5283)
**Dependencies**: None
**Merge deadline**: None
**Testing instructions**:
1. run `make pull`
2. verify that it pulls the same image used as the base for the docker image
**Reviewers**

SE-3692 Update make pull so it pulls the correct image

---

blockstore/apps/bundles/storage.py
blockstore/apps/bundles/store.py
blockstore/apps/bundles/tests/test_storage.py
blockstore/settings/base.py

This will help fix a long-running bug; specifically:
* Blockstore generates signed URLs in order to grant
temporary access to snapshot/draft asset files when
using S3 as a backend (as it does on edx.org).
* These signed URLs are meant to be valid for ~24-48
hours, allowing clients and users to visit or cache
the links for a reasonable amount of time,
but still having them expire eventually in order
to prevent free access to copyrighted content.
* However, blockstore.edx.org is configured with
a temporary IAM credential, which can expire at
any time, and lasts only an hour at max. So, URLs
signed with these temporary credentials are
at risk of expiring at any time.
As a fix, This commit introduces two new Django settings:
* BUNDLE_ASSET_URL_STORAGE_KEY
* BUNDLE_ASSET_URL_STORAGE_SECRET
If …

feat: allow config of storage backend for longer-lived urls

---

Makefile
blockstore/apps/api/v1/serializers/drafts.py
blockstore/apps/api/v1/tests/helpers.py
blockstore/apps/api/v1/views/drafts.py
blockstore/apps/bundles/models.py
blockstore/apps/bundles/storage.py
blockstore/apps/bundles/store.py
requirements/base.txt
requirements/constraints.txt
requirements/docs.txt
requirements/local.txt
requirements/pip-tools.txt
requirements/production.txt
requirements/test.txt
tagstore/backends/django.py
tagstore/models/tag.py

In this PR, we:
* modify requirements constraints to fix the requirements upgrade job,
* upgrade requirements pins, and
* fix the build issues resulting from the upgraded pins.
See individual commits for more detail.
I ran unit tests and quality checks locally. I plan to deploy Blockstore to production shortly after merging.
**Urgency: Moderate-low.** While not causing production issues, T&L gets alerted every week when the requirements job fails. Also, Blockstore goes months without being deployed, which isn't great (what if the pipeline stops working and we don't notice?). By getting the weekly upgrade cadence going again, we can keep version pins fresh and ensure we're deploying regularly.

Fix and re-run requirements upgrade

---

requirements/constraints.txt
requirements/pip-tools.txt

Now that we are have pinned pip to version 20.3.4 in configuration, which is compatible with the latest version of pip-tools according to this compatibility chart
https://github.com/jazzband/pip-tools/#versions-and-compatibility
So in this PR, we are upgrading the latest pip-tools.
Relevant JIRA: https://openedx.atlassian.net/browse/BOM-2247

BOM-2247 - Upgrade pip-tools

---

requirements/base.txt
requirements/constraints.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

Include [common_constraints](https://github.com/edx/edx-lint/blob/master/edx_lint/files/common_constraints.txt) file in Python requirements compiling process. The includes constraints to avoid versions of Python packages that are known to be problematic across Open edX repositories.
After running `make upgrade` again, social-auth-core and pyjwt and both downgraded. This should fix an issue in which the LMS->Blockstore SSO flow is failing to complete, preventing users from accessing the Blockstore Django admin panel.
https://openedx.atlassian.net/browse/TNL-8609 
Setup:
* Follow the [Blockstore devstack setup instructions](https://github.com/edx/blockstore#using-with-docker-devstack) if you haven't already.
* Start devstack LMS
Replicate bug:
* Check out blockstore master
* Start …

fix: fix SSO by constraining requirements using common_constraints

---

requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

The original [django-environ](https://github.com/joke2k/django-environ) package doesn't seem to be maintained and despite other prompts (joke2k/django-environ#292 and joke2k/django-environ#282) it doesn't look like the maintainer is not interested in bringing it back to life.
A fork was created, [django-environ-2](https://pypi.org/project/django-environ-2/), and that one is actively maintained and currently supports Django 3.2.
edx/upgrades#21
Run `make easyserver`.

Use django-enviro-2 instead of deprecated django-environ

---

requirements/base.in
requirements/base.txt
requirements/docs.in
requirements/docs.txt
requirements/github.in
requirements/local.txt
requirements/production.txt
requirements/test.txt

Inspired by a recent Django 3.2 upgrade talk, I looked at our TNL-owned repos for requirement constraints. This repo has two requirement constraints that no longer need to be present, due to recent code releases of the packages. Removing these constraints will make it easier on the Django 3.2 upgrade team to upgrade the whole of Open edX platform.
Verify the CI passes.

Remove outdated dependency constraints

---

requirements/base.in
requirements/base.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

This PR removes `djangoresframework-expander` library that's not being used.
Empty searches:
- expander
- ExpanderSerializerMixin
- djangorestframework-expander

chore: remove unused djangoresframework-expander library

---

CHANGELOG.rst
Makefile
blockstore/__init__.py
blockstore/apps/api/__init__.py
blockstore/apps/api/data.py
blockstore/apps/api/exceptions.py
blockstore/apps/api/methods.py
blockstore/apps/api/tests/test_blockstore_api.py
blockstore/apps/bundles/links.py
blockstore/apps/bundles/migrations/0003_update_character_set.py
blockstore/apps/bundles/models.py
blockstore/apps/bundles/storage.py
blockstore/apps/bundles/tests/test_storage.py
blockstore/settings/base.py

Continues the work started by https://github.com/openedx/blockstore/pull/140, and makes the remaining changes necessary for the Blockstore as app ADR: [#71](https://github.com/openedx/blockstore/pull/71).
Replaces https://github.com/openedx/blockstore/pull/97.
See https://github.com/openedx/blockstore/pull/97 for discussions.
See https://github.com/openedx/edx-platform/pull/29779.
Once these PRs merge, we will need to:
Clean up the edx-platform codebase:
Clean up the blockstore codebase:

 [BD-14] Updates Blockstore Python API [TNL-8746] [FAL-2702]

---

blockstore/__init__.py
blockstore/apps/bundles/storage.py
blockstore/apps/bundles/store.py
blockstore/apps/bundles/tests/test_storage.py

Adds info-level logging to help debug issues with blockstore storage configuration.
Improves the storage configuration tests to further clarify effects of different configurations.
No functionality has been changed here -- it's just logging and tests.
We test the blockstore storage configuration options quite thoroughly -- the test most relevant to edx.org's configured deployment of blockstore-as-an-app is: [`test_asset_storage_long_lived_urls_enabled`](https://github.com/open-craft/blockstore/blob/jill/blockstore-storage-logging/blockstore/apps/bundles/tests/test_storage.py#L148-L182). It demonstrates [these storage settings](https://github.com/open-craft/blockstore/blob/jill/blockstore-storage-logging/blockstore/apps/bundles/tests/test_storage.py#L54-L71), which show how top-level …

[BD-14] test: adds storage config logging and improves tests

---

blockstore/__init__.py
blockstore/apps/bundles/storage.py
blockstore/apps/bundles/tests/test_storage.py

Updates https://github.com/openedx/blockstore/pull/183 to remove the other reference to `access_key` in logging,
and to fix the tests so they're no longer breaking, and also better match edX's blockstore storage config.

[BD-14] fix: remove refrence to access key in logging

---

blockstore/__init__.py
setup.py

This repository's setup.py was configured
such that only the root Python package (`blockstore`)
was included, not sub-packages (`blockstore.apps`, etc.).
This commit fixes that by using `find_packages(...)`.
A similar fix was made to the cookiecutter repository
here: https://github.com/openedx/edx-cookiecutters/pull/257
The implication of the misconfiguration was that
blockstore could be installed in *editable* mode,
but not as a built package:
pip install -e git+https://github.com/openedx/blockstore.git@1.2.4#egg=blockstore==1.2.4
python -c "from blockstore import apps"
pip install "blockstore @ git+https://github.com/openedx/blockstore.git@1.2.4"
python -c "from blockstore import apps"
If not fixed, this would become a problem when blockstore
is pushed to PyPI and installed as just:
pip …

build: include sub-packages in wheel (and bump to 1.2.5)

---

README.rst
catalog-info.yaml

This updates the README and adds `catalog-info.yaml` file per the requirements of OEP-55 and the [Maintainership Pilot](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Maintainership+Pilot)

Update README and catalog-info.yaml per maintainers pilot.

---

README.rst

Now that https://github.com/openedx/frontend-app-library-authoring/pull/50 has merged, we can update the link in the README.

docs: update README link now that tutor plugin PR has merged

---

requirements/base.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

Updates `django` from `3.2.16` to `3.2.17`

chore: Updating Python Requirements

---

CHANGELOG.rst
blockstore/__init__.py
blockstore/apps/bundles/admin.py
blockstore/apps/bundles/models.py

fix: allow bundles to be created via django admin
Previously, trying to create a bundle would lead to the
message:
IntegrityError at /admin/bundles/bundle/add/
(1048, "Column 'collection_id' cannot be null")
because `collection` was indeed a required field, but
it was marked as editable=False, so it one could not
actually set it when making a new bundle.
With this change, we set editable=True, and add
some logic to the admin site so that the
`collection` field can be set when a bundle
is first created, but not afterwards.
This will trigger a migration, but since `editable`
is purely a Django-level validation field, no
changes should be seen in the MySQL schema.
N/A
Get blockstore running in a dev env, and make sure at least one Collection is created. I chose to use Tutor plus the [library …

fix: allow bundles to be created via django admin

---

blockstore/apps/rest_api/v1/views/bundles.py

There could be a lot of bundles, so we can't use query params
because it will raise the "Request-URI Too Long" error. Use the
request data in such a case.

[BD-14] fix: bundles list view Request-URI Too Long error

---

requirements/docs.in
requirements/docs.txt
requirements/local.txt

The edx-sphinx theme is being deprecated, and replaced with sphinx-book-theme.
This removes references to the deprecated theme and replaces them with the new
standard theme for the platform.
See openedx/edx-sphinx-theme#184

chore: Switch from edx-sphinx-theme to sphinx-book-theme

---

requirements/base.txt
requirements/local.txt
requirements/production.txt
requirements/test.txt

This PR updates Django to version 3.2.23 in the Quince release branch. The update includes the latest security patch, as part of the BTR working group's ongoing efforts to ensure the security of Open edX's supported named releases.
For more information, see: [https://github.com/openedx/wg-build-test-release/issues/324](https://github.com/openedx/wg-build-test-release/issues/324)

chore: update Django to 3.2.23 for Quince - Security Patch
